/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.grafos;

import projeto.projetografos.LerArquivo;


/**
 *
 * @author usuario
 */
public class Tela1 extends javax.swing.JFrame {

  
    
    public Tela2 tela2;
    
    
    
    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
        this.tela2 = new Tela2();
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caixaEntrada1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("** CONVERSOR PARA GRAFO DE ARESTA **");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 500, 50);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite o nome do arquivo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 250, 250, 19);

        caixaEntrada1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                caixaEntrada1ComponentAdded(evt);
            }
        });
        caixaEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaEntrada1ActionPerformed(evt);
            }
        });
        getContentPane().add(caixaEntrada1);
        caixaEntrada1.setBounds(40, 280, 470, 40);

        jButton1.setText("Converter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 280, 130, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/projetografos/Imagem2/1643282225711.jpeg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(2000, 1500));
        jLabel3.setMinimumSize(new java.awt.Dimension(1280, 1000));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -10, 1310, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaEntrada1ActionPerformed
      
        
    }//GEN-LAST:event_caixaEntrada1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


this.tela2.setVisible(true); 
this.tela2.transmissor = this.caixaEntrada1.getText();

LerArquivo lerArquivo = new LerArquivo(this.tela2.transmissor);
this.tela2.transmissor = lerArquivo.getConteudoArquivo();

        
    


    }//GEN-LAST:event_jButton1ActionPerformed

    private void caixaEntrada1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_caixaEntrada1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaEntrada1ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField caixaEntrada1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
